## eps_AB = +1 if A, -1 if B, 0 if not A nor B

In [5]:
import sys,os
import numpy as np
from scipy import linalg
from sklearn.preprocessing import OneHotEncoder

In [6]:
n = 2 # number of variables
m = 3 # number of states of each variables
l = 3 # sample size

# original
s0 = np.array([[1,2],[0,1],[2,1]])
print(s0)

[[1 2]
 [0 1]
 [2 1]]


In [7]:
def eps_ab(s0,m):
    l,n = s0.shape
    eps = np.zeros((n,l,m,m))
    for i in range(n):
        for t in range(l):
            eps[i,t,:,int(s0[t,i])] = -1.
            eps[i,t,int(s0[t,i]),:] = 1.
    return eps

In [8]:
eps_all = eps_ab(s0,m)

eps = eps_all[0]
print(eps)

[[[ 0. -1.  0.]
  [ 1.  1.  1.]
  [ 0. -1.  0.]]

 [[ 1.  1.  1.]
  [-1.  0.  0.]
  [-1.  0.  0.]]

 [[ 0.  0. -1.]
  [ 0.  0. -1.]
  [ 1.  1.  1.]]]


In [9]:
print(eps_all[1])

[[[ 0.  0. -1.]
  [ 0.  0. -1.]
  [ 1.  1.  1.]]

 [[ 0. -1.  0.]
  [ 1.  1.  1.]
  [ 0. -1.  0.]]

 [[ 0. -1.  0.]
  [ 1.  1.  1.]
  [ 0. -1.  0.]]]
