In [1]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

n = 3 # number of variables
m = 2 # number of states of each variables

# original
s0 = np.array([[1,0,1],[1,0,0],[1,1,0]])
print(s0)

# onehot encoding
enc = OneHotEncoder(n_values=m)
s = enc.fit_transform(s0).toarray()
print(s)

[[1 0 1]
 [1 0 0]
 [1 1 0]]
[[0. 1. 1. 0. 0. 1.]
 [0. 1. 1. 0. 1. 0.]
 [0. 1. 0. 1. 1. 0.]]


In [2]:
# recover s0 from s
s_inverse = np.argmax(s.reshape(-1,m),axis=1).reshape(-1,n)
print(s_inverse)

[[1 0 1]
 [1 0 0]
 [1 1 0]]
