# test Monte Carlo

In [1]:
import sys
import numpy as np
from scipy import linalg
from sklearn.preprocessing import OneHotEncoder

import matplotlib.pyplot as plt
%matplotlib inline

#import inference
#import fem

In [2]:
# setting parameter:
np.random.seed(1)

n = 2 # number of positions
m = 3 # number of values at each position
l = 5

g = 2.

nm = n*m

In [3]:
def itab(n,m):    
    i1 = np.zeros(n)
    i2 = np.zeros(n)
    for i in range(n):
        i1[i] = i*m
        i2[i] = (i+1)*m

    return i1.astype(int),i2.astype(int)

In [4]:
nm = n*m
w = np.random.normal(0.0,g/np.sqrt(nm),size=(nm,nm))

In [5]:
i1tab,i2tab = itab(n,m)

In [6]:
# initial s (categorical variables)
s_ini = np.random.randint(0,m,size=(l,n)) # integer values
#print(s_ini)

# onehot encoder 
enc = OneHotEncoder(n_values=m)
s = enc.fit_transform(s_ini).toarray()
print(s)

[[0. 1. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 1.]
 [0. 0. 1. 1. 0. 0.]
 [1. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 1. 0.]]


In [8]:
#t = 0
#irepeat = 0
i = 0

i1,i2 = i1tab[i],i2tab[i]

h = s.dot(w[i1:i2,:].T)
print(h.shape)

(5, 3)


In [10]:
e = (s[:,i1:i2]*h).sum(axis=1)
print(e)

[-0.82513289  0.20895048  0.02766141  2.03287481  0.5722833 ]


In [9]:
e = (s[:,i1:i2]*h).sum(axis=1)
print(e)

[[-0.         -0.82513289 -0.        ]
 [-0.         -0.          0.20895048]
 [-0.          0.          0.02766141]
 [ 2.03287481  0.         -0.        ]
 [ 0.          0.5722833  -0.        ]]


In [11]:
k = np.random.randint(0,m,size=l)
print(k)

[0 0 1 1 2]


In [16]:
#e_new = np.empty(l)
#for t in range(l):
#    e_new[t] = h[t,k[t]]
#print(e_new)
#print(type(e_new))

[-1.37557223 -2.31044891  0.05688427  2.61843897 -0.45436611]
<type 'numpy.ndarray'>


In [18]:
e_new = [h[t,k[t]] for t in range(l)]
print(e_new)

[-1.3755722315391408, -2.310448906741323, 0.05688427215092476, 2.6184389713897422, -0.4543661093975928]


In [19]:
print(e)

[-0.82513289  0.20895048  0.02766141  2.03287481  0.5722833 ]


In [21]:
t0 = np.exp(e_new - e) > np.random.rand(l)
print(t0)

[ True False  True  True  True]


In [22]:
for t in range(l):
    if t0[t]: 
        s[t,i1:i2] = 0.
        s[t,i1+k[t]] = 1.
            

0
2
3
4
